# Generated by Django 5.1.1 on 2024-11-03 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmes', '0002_alter_filme_atores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Não pode ser avaliado abaixo de zero'), django.core.validators.MaxValueValidator(5, 'Não pode ser avaliado com valor acima de cinco')])),
                ('cometario', models.TextField(blank=True, null=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='filmes.filme')),
            ],
        ),
    ]
