# Generated by Django 5.1.1 on 2024-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0002_generomodel_delete_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('idade', models.FloatField()),
            ],
        ),
    ]
