# Generated by Django 5.1.1 on 2024-10-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0003_atormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtorModel',
        ),
    ]
